import Head from "next/head";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillMail,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import myImage from "../public/myImage.jpg";
import Image from "next/image";
import Skills from "./components/skills";
//import TestimonialScroller from "./components/TestimonialScroller";
import SkillsPhases from "./components/SkillsPhases";
import ProjectsSection from "./components/ProjectsSection";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Nithya&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-wheat px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedby</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8 "
                  target="_blank" href="/Resume.pdf"
                  rel="noreferrer"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:mt-0 md:h-96 md:w-96">
          <Image src={myImage} fill={true} style={{ objectFit: 'cover' }} alt="myImage" />

          </div>

          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Nithya M S
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Full stack Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Full-stack developer and designer, passionate about creating innovative solutions. Let&apos;s connect and explore opportunities!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a target="_blank" href="https://github.com/Nithyams17" rel="noreferrer" className="hover:scale-125 hover:rotate-12 transition-all duration-300 cursor-pointer hover:text-black dark:hover:text-white hover:shadow-lg hover:shadow-gray-500/50">
                <AiFillGithub />
              </a>
              <a target="_blank" href="https://www.linkedin.com/in/nithya-m-s-328893319" rel="noreferrer" className="hover:scale-125 hover:rotate-12 transition-all duration-300 cursor-pointer hover:text-blue-600 dark:hover:text-blue-400 hover:shadow-lg hover:shadow-blue-500/50">
                <AiFillLinkedin />
              </a>
              <a target="_blank" href="mailto:nithyagowdaa1727@gmail.com" rel="noreferrer" className="hover:scale-125 hover:rotate-12 transition-all duration-300 cursor-pointer hover:text-red-500 dark:hover:text-red-400 hover:shadow-lg hover:shadow-red-500/50">
                <AiFillMail />
              </a>
            </div>


          </div>
        </section>

        <Skills />

        <ProjectsSection />

        <SkillsPhases />
      </main>

      <footer className="text-center">
        <div className="border-t border-gray-300 py-2">
          <p className="text-gray-600">
            Phone: <a href="tel:+91 8431874154">+91 8431874154</a>
          </p>
          <p className="text-gray-600">
            Email: <a href="mailto:nithyagowdaa1727@gmail.com">nithyagowdaa1727@gmail.com</a>
          </p>
        </div>
      </footer>
    </div>
  );
}
